elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  image: kibana:latest
  ports:
    - "5601:5601"
  links:
    - elasticsearch
